import { Tool, ToolCategory } from './types';

// Simulating Notion Database Export for Content Creation Tools
export const AI_TOOLS_DATA: Tool[] = [
  {
    id: '1',
    name: 'Jasper AI',
    description: 'The industry standard for AI marketing copy, blog posts, and brand voice consistency.',
    category: ToolCategory.TEXT,
    affiliateLink: 'https://jasper.ai?fpr=your-id',
    priceModel: 'Paid',
    rating: 4.8,
    monthlyVisits: '5M+',
    imageUrl: 'https://picsum.photos/400/200?random=1',
    features: ['Brand Voice', 'SEO Mode', 'Marketing Templates', 'Chrome Extension', '25+ Languages'],
    offer: '7-Day Free Trial'
  },
  {
    id: '2',
    name: 'Midjourney',
    description: 'Create award-winning realistic images and art from text prompts via Discord.',
    category: ToolCategory.IMAGE,
    affiliateLink: 'https://midjourney.com',
    priceModel: 'Paid',
    rating: 4.9,
    monthlyVisits: '15M+',
    imageUrl: 'https://picsum.photos/400/200?random=2',
    features: ['Photorealism', 'V6 Model', 'Discord Interface', 'Region Vary', 'Style Tuner']
  },
  {
    id: '3',
    name: 'Copy.ai',
    description: 'Automate your content workflow. Great for social media captions and email sequences.',
    category: ToolCategory.TEXT,
    affiliateLink: 'https://copy.ai?ref=your-id',
    priceModel: 'Freemium',
    rating: 4.6,
    monthlyVisits: '3M+',
    imageUrl: 'https://picsum.photos/400/200?random=3',
    features: ['Workflow Automation', 'Unlimited Words (Pro)', 'Chat'],
    offer: '40% Off Annual Plan'
  },
  {
    id: '4',
    name: 'Runway',
    description: 'Professional video generation and editing. Text-to-video and video-to-video transformation.',
    category: ToolCategory.VIDEO,
    affiliateLink: 'https://runwayml.com?ref=your-id',
    priceModel: 'Freemium',
    rating: 4.7,
    monthlyVisits: '2M+',
    imageUrl: 'https://picsum.photos/400/200?random=4',
    features: ['Gen-2 Model', 'Motion Brush', 'Green Screen']
  },
  {
    id: '5',
    name: 'ElevenLabs',
    description: 'Generate top-quality spoken audio in any voice and style. Best for narration.',
    category: ToolCategory.AUDIO,
    affiliateLink: 'https://elevenlabs.io/?from=your-id',
    priceModel: 'Freemium',
    rating: 4.9,
    monthlyVisits: '8M+',
    imageUrl: 'https://picsum.photos/400/200?random=5',
    features: ['Voice Cloning', 'Dubbing Studio', 'Low Latency'],
    offer: '1st Month for $1'
  },
  {
    id: '6',
    name: 'Opus Clip',
    description: 'Repurpose long videos into viral shorts in one click using AI curation.',
    category: ToolCategory.VIDEO,
    affiliateLink: 'https://opus.pro?ref=your-id',
    priceModel: 'Freemium',
    rating: 4.8,
    monthlyVisits: '4M+',
    imageUrl: 'https://picsum.photos/400/200?random=6',
    features: ['Auto-Captioning', 'Virality Score', 'Face Focus'],
    offer: 'Free Forever Plan'
  },
  {
    id: '7',
    name: 'Synthesia',
    description: 'Turn text into videos with AI avatars. No cameras or actors needed.',
    category: ToolCategory.VIDEO,
    affiliateLink: 'https://synthesia.io/?via=your-id',
    priceModel: 'Paid',
    rating: 4.5,
    monthlyVisits: '1M+',
    imageUrl: 'https://picsum.photos/400/200?random=7',
    features: ['160+ Avatars', '120+ Languages', 'Script Assistant']
  },
  {
    id: '8',
    name: 'HypeFury',
    description: 'Your personal assistant for growing & monetizing your Twitter/X audience.',
    category: ToolCategory.SOCIAL,
    affiliateLink: 'https://hypefury.com?via=your-id',
    priceModel: 'Paid',
    rating: 4.7,
    monthlyVisits: '500k+',
    imageUrl: 'https://picsum.photos/400/200?random=8',
    features: ['Auto-Plug', 'Thread Maker', 'Evergreen Slots']
  },
  {
    id: '9',
    name: 'Descript',
    description: 'Edit audio and video by editing text. Includes studio sound and overdub.',
    category: ToolCategory.AUDIO,
    affiliateLink: 'https://descript.com?lmref=your-id',
    priceModel: 'Freemium',
    rating: 4.7,
    monthlyVisits: '2.5M+',
    imageUrl: 'https://picsum.photos/400/200?random=9',
    features: ['Text-Based Editing', 'Studio Sound', 'Eye Contact Fix'],
    offer: '1 Free Hour/Mo'
  },
  {
    id: '10',
    name: 'Leonardo.Ai',
    description: 'Create production-quality visual assets for your projects with speed and style consistency.',
    category: ToolCategory.IMAGE,
    affiliateLink: 'https://leonardo.ai?via=your-id',
    priceModel: 'Freemium',
    rating: 4.8,
    monthlyVisits: '12M+',
    imageUrl: 'https://picsum.photos/400/200?random=10',
    features: ['Image Guidance', 'Real-time Canvas', '3D Texture Gen']
  },
  {
    id: '11',
    name: 'Surfer SEO',
    description: 'Boost your organic traffic with an AI-driven content intelligence strategy.',
    category: ToolCategory.TEXT,
    affiliateLink: 'https://surferseo.com?fpr=your-id',
    priceModel: 'Paid',
    rating: 4.6,
    monthlyVisits: '800k+',
    imageUrl: 'https://picsum.photos/400/200?random=11',
    features: ['Content Editor', 'Keyword Research', 'Audit'],
    offer: '7-Day Money Back'
  },
  {
    id: '12',
    name: 'InVideo',
    description: 'Turn ideas into videos instantly. Great for YouTube and Social Media.',
    category: ToolCategory.VIDEO,
    affiliateLink: 'https://invideo.io?ref=your-id',
    priceModel: 'Freemium',
    rating: 4.5,
    monthlyVisits: '6M+',
    imageUrl: 'https://picsum.photos/400/200?random=12',
    features: ['5000+ Templates', 'Stock Media', 'AI Script Gen']
  },
  {
    id: '13',
    name: 'Taskade',
    description: 'AI-powered productivity workspace for teams. Mind maps, lists, and chat.',
    category: ToolCategory.PRODUCTIVITY,
    affiliateLink: 'https://taskade.com?via=your-id',
    priceModel: 'Freemium',
    rating: 4.7,
    monthlyVisits: '2M+',
    imageUrl: 'https://picsum.photos/400/200?random=13',
    features: ['AI Agents', 'Workflow Automation', 'Team Chat'],
    offer: 'Free Forever Plan'
  },
  {
    id: '14',
    name: 'Otter.ai',
    description: 'AI meeting assistant that records audio, writes notes, and captures slides.',
    category: ToolCategory.PRODUCTIVITY,
    affiliateLink: 'https://otter.ai/referrals/your-id',
    priceModel: 'Freemium',
    rating: 4.6,
    monthlyVisits: '5M+',
    imageUrl: 'https://picsum.photos/400/200?random=14',
    features: ['Real-time Transcripts', 'Meeting Summary', 'Speaker ID']
  },
  {
    id: '15',
    name: 'FeedHive',
    description: 'AI social media management tool for scheduling and recycling content.',
    category: ToolCategory.SOCIAL,
    affiliateLink: 'https://feedhive.com?fpr=your-id',
    priceModel: 'Paid',
    rating: 4.8,
    monthlyVisits: '300k+',
    imageUrl: 'https://picsum.photos/400/200?random=15',
    features: ['AI Post Prediction', 'Recycling', 'Collaboration']
  }
];